[package]
name = "hackernews-sycamore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
async-recursion = "0.3.2"
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
futures = "0.3.17"
log = "0.4.14"
reqwasm = "0.2.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "a2d7275" }
sycamore-router = { git = "https://github.com/sycamore-rs/sycamore", rev = "a2d7275" }
web-sys = { version = "0.3.53", features = ["Url"] }
