[[hooks]]
stage = "build"
command = "node"
command_arguments = [
    "node_modules/tailwindcss-cli",
    "build",
    "-i",
    "src/tailwind.css",
    "-o",
    "dist/.stage/tailwind.css",
    "--jit"
]
